name: Build-Push-ghcr
on:
  push:
    branches: [ main ]
 
  pull_request:
 
    branches: [ main ]
    
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push preprocess to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./kfpboston/steps/preprocess
          tags: ghcr.io/jaredallencarterjac/preprocess:latest
          push: true
      - name: Push train to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./kfpboston/steps/train
          tags: ghcr.io/jaredallencarterjac/train:latest
          push: true
      - name: Push test to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./kfpboston/steps/test
          tags: ghcr.io/jaredallencarterjac/test:latest
          push: true
      - name: Push deploy to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./kfpboston/steps/deploy
          tags: ghcr.io/jaredallencarterjac/deploy:latest
          push: true
